default_install_hook_types: [pre-commit, commit-msg, post-commit]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: 
          - post-commit
          - pre-push

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix,--exit-non-zero-on-fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        language_version: python3.10

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.0
    hooks:
    # Update the uv lockfile
      - id: uv-lock
